### ISSUE TITLE
Going to /accountSettings with no user signed in works

### ISSUE THREAD

**Issue by ninesalt** [Mshokrr/Arabesque#2]
When manually changing the url to /accountSettings when a user is not signed in, the page changes to show empty account settings and details. Only allow signed in users to access this page.

**Comment by Mshokrr** [comment]
Add the following to accountSettingsCtrl.js 

(function unAuthorizedAccess(){
    if (AuthSrv.getToken() === undefined) {
        $location.url("/");
        }
})();

Add it to the top of accountCtrl too if the same bug happens when accessing "/account"
