### ISSUE TITLE
navbar components don't work once signed in

### ISSUE THREAD

**Issue by ninesalt** [Mshokrr/Arabesque#4]
Consider changing elements in navbar when a user signs in to redirect to a new page which shows the content in a new page that only signed in users can see. For example, a cleaner gallery and projects interface.

Also consider not having a navbar once signed in to streamline dashboard look (ie: move navbar from index.html to main.html)

**Comment by ninesalt** [comment]
What do you think of this? Should the dashboard look like this? 

![image](https://cloud.githubusercontent.com/assets/7952255/18148650/41cad8d8-6fdb-11e6-9481-2f1835953fd3.png)

**Comment by Mshokrr** [comment]
actually here we have too much elements we dont need, so i suggest that we have 2 tabs,
the first one is the projects the is participating in and the second is the account and the account settings tab

**Comment by ninesalt** [comment]
![image](https://cloud.githubusercontent.com/assets/7952255/18173102/a16ab2ee-7068-11e6-8698-81207166a764.png)

What do you think? I tried the tabs but I think this looks (and works) a lot better
